export const PREDEFINED_INTERESTS = {
  Sports: [
    "Football",
    "Basketball",
    "Tennis",
    "Fitness",
    "Yoga",
    "Running",
    "Natation",
    "Cyclisme",
    "Randonnée",
    "Danse",
  ],
  Culture: [
    "Cinéma",
    "Musique",
    "Lecture",
    "Art",
    "Théâtre",
    "Musées",
    "Photographie",
    "Écriture",
    "Mode",
    "Histoire",
  ],
  Loisirs: [
    "Cuisine",
    "Voyages",
    "Gaming",
    "Jardinage",
    "Bricolage",
    "Shopping",
    "Méditation",
    "Collection",
    "Camping",
    "Peinture",
  ],
  Social: [
    "Fêtes",
    "Bénévolat",
    "Networking",
    "Langues étrangères",
    "Politique",
    "Associations",
    "Débats",
    "Œnologie",
    "Gastronomie",
  ],
  Tech: [
    "Programmation",
    "Jeux vidéo",
    "Intelligence artificielle",
    "Réseaux sociaux",
    "Nouvelles technologies",
    "Blockchain",
    "Robotique",
    "Domotique",
  ],
  Nature: [
    "Écologie",
    "Animaux",
    "Plantes",
    "Développement durable",
    "Agriculture",
    "Astronomie",
    "Météo",
  ],
  Bien_être: [
    "Spiritualité",
    "Développement personnel",
    "Nutrition",
    "Santé",
    "Sport extrême",
    "Relaxation",
    "Médecines douces",
  ],
  Créativité: [
    "DIY",
    "Artisanat",
    "Design",
    "Architecture",
    "Couture",
    "Dessin",
    "Musique",
    "Chant",
  ],
};
